appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c310760302eb707003bbce1
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: eciDlI1fWwZB0C7jGwR6Ksa9FMdM7Tfa+s5bWZESodnB2DdnDgZKiMyO6y3c4HWHbxsHvxNFhBCVag9QoukU3kXaUUWFCRQCbNxfutf6RNp3G0YeNjVfMZ56kGhUdF98+A/P16cG1+P9DvpVMhq4LvNEEImS8+Cv7Xp8WlDORI38k9gM/Nr+KMkC1Bb58xUdsfe5rXYmjbcR43t6NznhmRBnuZk+EHrjVBHP5bRg1wQhrGzXNfW2XQkZgTVigMcbpXlw2bJPgMsB7Lzh0GWU5QZwblLPnxdIlILBBa+uXmIB7rYvSvFm5MqCRbaEM8/pYLsA38pq3xkOYNHsvTSKWSstVuzmuvloygSaDwiuFTpsPZ1+v8bBE4/3C31GsqoglZ0jcNgM6S0by7e3kesiiIXKdJ4XLTFHwh7zfM13CDO9gbXl/J4chjuSgcExPkR3Hx/0ZvgYKqEqJS4+Er+iDtowaPAJYwCqfRqAAZg+g1/e/phA5ZeTrTqOfn4LDju4CY2yh/F2wWBlfnmWq0KgxdvFLlHyoJnEvspePfVqq+sfKMFfkU1Rcd5Bi8ZUSTdKON4ZMr4L8yCk5yUY/FzrQaD6a0TItpcEtGpIZFTlpVbVVubhGN2Bp84qQR/eLcwcve8zW/nx5FtapVp+T+Ms5SdR1Mt62hmI3Wlv0XJ+3Kk=}
